### PR TITLE
build: Rollup before running tests

### PR DESCRIPTION
**Pull request by ynnoj**

### CODE REVIEW

**Comment by zot24** [comment]
atm when assigning a reviewer to a PR like this add that person as a assignee too and change the PR pipeline to `review` so we can see it in our boards and know that needs a review for our end, like so:

boards_ _moltin_workflow

**Comment by ynnoj** [comment]
@zot24 I don't use ZenHub 💩

**Comment by zot24** [comment]
@ynnoj it doesn't matter we do, so even if you don't use it follow does steps and you'll be helping the team to help you, it's a win win 😄

**Comment by ynnoj** [comment]
@zot24 How do you expect me to move the PR pipeline when I don't have ZenHub installed? 🤦‍♂️ 

Anyway, this is a discussion to be had elsewhere.

**Pull request merged**
