### PR TITLE
feat: Allow sending flow data when updating cart items

### PR DESCRIPTION
**Pull request by s-soltys**
## Status

* ✅ Ready

## Type

* ### Feature
  Implements a new feature 

## Description

This feature makes it possible to enrich the `Cart UpdateItemQuantity` endpoint with additional Flow data. This is currently supported by the API but not reflected in the documentation or in the SDK.

## Notes

The name of the method `UpdateItemQuantity` seems to narrow. We should consider renaming it to a more general name.
`UpdateItem` sounds accurate.

### CODE REVIEW

**Comment by ynnoj** [comment]
Agreed @notrab. Renaming the method would be a breaking change. I'd prefer the approach of adding a new method, and _perhaps_ deprecating `UpdateItemQuantity`.

Happy to merge this as it is. Do you want to create the follow up PR @s-soltys?

**Comment by s-soltys** [comment]
@ynnoj @notrab updated this PR to include a new `UpdateItem` method - I also agree this seems like the best approach.

**Comment by notrab** [comment]
Awesome update @s-soltys. Thanks for quick response and update. 😅

**Comment by s-soltys** [comment]
@notrab great! Shall we merge this? We'll need this additional method next week from the SDK ;)

**Comment by s-soltys** [comment]
@notrab @ynnoj shall we merge this?

**Comment by notrab** [comment]
@s-soltys thanks for the contribution 🤗

**Pull request merged**
