### PR TITLE
feat: Multiple gateways

### PR DESCRIPTION
**Pull request by sebin-ayata**
* ### Feature 

  Implements multiple gateway capability. 

  

* ### Test 

Modify testcases to cover current gateway implementation 

  

## Description 

  

*The current implementation model of gateway credential storage inhibits users from creating more than one instance of Moltin-gateway. Because when a new gateway is added it overwrites credentials of previous gateway instances as they write to the same cookie-storage/file-storage called 'moltincredentials'.* 

  

### Why do we need more than one gateway instance?  

1. One of the runtime where we use an SDK is in an Experience layer (popularly known as the [BFF layer](https://docs.microsoft.com/en-us/azure/architecture/patterns/backends-for-frontends)), where instead of directly calling Elastic-path APIs from client, we call it through some middleware in the backend. This approach helps users to cache frequent data from EP and to do data aggregation from various composable units (like Algolia (Search-engine), Ampliance (CMS), Fluent (OMS) etc.) for a better user experience in frontend. For this approach, the middleware needs both implicit-gateway as well as admin-gateway (with client-secret) within same runtime. 

  

2. To connect to different stores from the same back-end simultaneously through the corresponding gateway. 

  

### Proposal 

The idea is to introduce a gatewayId (as part of gateway configOptions) which we can append to  the current storage name- 'moltincredentials'. The default value of gatewayId will be a Unix timestamp but user can provide their own gatewayId (like admin, client etc) if they wish to. According to this, each gateway will have separate file/cookie named moltincredentials-${timestamp} in which its corresponding credentials can be stored independent of each other. Thus, in a node runtime (like in an Experience layer) each gateway can be used based on a singleton pattern.

### CODE REVIEW

**Comment by samblacklock** [comment]
thanks @sebin-ayata we will review asap.

**Comment by sjsam** [comment]
This is a much needed feature.

**Comment by field123** [comment]
Hi @sebin-ayata, we really appreciate contributions!

I have a couple of concerns about using `Date.now()` as a "default" gateway id:

- Current users of the sdk will be creating a new storage entry everytime the refresh their browser e.g. `moltinCredentials-1659364038362` then a refresh causes it to create `moltinCredentials-1659364049404` with no mechanism for clean up.
- If the user tries to create gateways at sub millisecond speeds then Date.now() will not provided a unique postfix for the storage entry and will cause a collision. This is possible [inside a loop](https://i.gyazo.com/9b2d17a6f42604c5942cce0104de59c5.png).

By setting a new "default" `moltinCredentials` storage key we would be breaking anyones code that depends on `moltinCredentials` being the key. I don't believe we have it documented anywhere that this is safe to assume but if we can avoid changing the default key value that would prefered.

Open question:

Are there any considerations to be made for others values that the sdk sets in the storage factories e.g. `mcurrency` or `mcart`

**Comment by field123** [comment]
Hi @sebin-ayata,

Closing https://github.com/moltin/js-sdk/pull/682 in favour of https://github.com/moltin/js-sdk/pull/714 please take a look at https://github.com/moltin/js-sdk/pull/714 and let me know if it handles everything you need it to.

**Pull request closed without merging**
