### PR TITLE
Removed nested namespaces

### PR DESCRIPTION
**Pull request by dusanradovanovic**
## Type

* ### Refactor
  A code change that neither fixes a bug nor adds a feature

## Description

This PR removes nested namespaces and only leaves main `moltina namespaces. It flattens the export structure so that all interfaces are directly exported. Without this change users of the library would have to define type as `categories.CategoryBase` and similar and carry namespaces to all function params etc.

### CODE REVIEW

**Comment by RyanKirby89** [comment]
@dusanradovanovic @shaunmaharaj This is interesting. This would have been my preferred approach (you might recall I spoke to you about this Shaun) however when I looked in to it, it seemed that best practiced suggested that it was better to keep services behind namespaces. Just want to make sure we deliberately want to take this out? I really don't mind either way, as stated, my preference was this initially - and I could be wrong, but when looking into it, is just seemed to me that best practice suggested namespaces, which is why I put them in - but then I am not an expert on SDK's so I could be wrong. :)

**Comment by agrohs** [comment]
Wow, this would be a pretty impactful change...hoping it stays as is

**Comment by shaunmaharaj** [comment]
@RyanKirby89 that's a good point regarding customers potentially creating their own interface definitions. From a readability POV, it makes sense for us to remove the nested namespaces to prevent situations of `Product.ProductBase.xxxxx`.

As for compatibility, we'll need to consider any customers/clients who are currently using this library and the impact it will have to them. It is not simply within the scope of our new touchpoints.

FYI @dusanradovanovic If we merge this, this PR is also missing the documentation update to the README that @RyanKirby89 mentioned. Documentation will need to be updated to reflect this and we'll need to ensure the storefront is using the correct structure.

**Comment by dusanradovanovic** [comment]
Technically this is a breaking change, but only for customers who are using TypeScript and who started utilizing types from v3.24 (which was published a week ago) in their code. If you just upgraded to 3.24 a week ago and didn’t change your client code, then this is not going to be a breaking even if you are using TypeScript. Even if you are using TypeScripts and you've started adapting your code to take advantage of the types from 3.24 the impact is minimal as you only need to remove the namespace part from the types.

**Comment by shaunmaharaj** [comment]
Considering the past few PRs have been major updates to the SDK, we should also update the release to a major version (v4.0.0) to illustrate these changes.

**Comment by shaunmaharaj** [comment]
@dusanradovanovic @RyanKirby89 Is this PR still needed after the latest SDK changes? Can we close?

**Pull request closed without merging**
